---
- name: "pam | Deploy pam services"
  ansible.builtin.template:
    src: "pam.j2"
    dest: "{{ '/etc/pam.d/' + vars['outer_item'] }}"
    group: "root"
    owner: "root"
    mode: "0644"
    force: "yes"
  loop: "{{ hostvars[inventory_hostname]['pam'] |
    community.general.json_query(\"[?service=='\" + vars['outer_item'] +
    \"']\") | flatten(levels=1) }}"
  loop_control:
    label: "{{ vars['outer_item'] }}"
