---
- name: "pam | Include pre requisite tasks"
  ansible.builtin.import_tasks:
    file: "pre_requisite.yml"
- name: "pam | Include executor tasks"
  ansible.builtin.import_tasks:
    file: "pam_executor.yml"
