---
- ansible.builtin.include_tasks:
    file: "deploy_pam.yml"
  loop: "{{ vars['pam_services'] | flatten(levels=1) }}"
  loop_control:
    loop_var: "outer_item"
  when:
    - "vars['pam_services'] is defined"
