---
- name: pam | Make pam.d directory
  file:
    path: "/etc/pam.d"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
- name: pam | Set facts about pam services
  set_fact:
    pam_services: "{{ hostvars[inventory_hostname]['pam'] |
                      json_query('[].service') }}"
