---
- name: pam | Make pam.d
  file:
    path: "/etc/pam.d"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
  register: "pam_d"
- name: pam | Set facts about pam services
  set_fact:
    pam_services: "{{ hostvars[inventory_hostname]['pam'] | json_query('[].service') }}"
  when:
  - "hostvars[inventory_hostname]['pam'] is defined"
  - "hostvars[inventory_hostname]['pam'] != ''"
  - "pam_d|success"
