---
- name: "pam | Make pam.d directory"
  ansible.builtin.file:
    path: "/etc/pam.d"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
- name: "pam | Set facts about pam services"
  ansible.builtin.set_fact:
    pam_services: "{{ hostvars[inventory_hostname]['pam'] |
      community.general.json_query('[].service') }}"
